#!/bin/sh

rm -f config.log config.status confdefs.h autom4te.cache \
    src/Makevars src/libRQuantLib.a src/libRQuantLib.def src/*.o src/*.so src/symbols.rds \
    RcppSrc/*.a RcppSrc/*.o RcppSrc/config.* inst/Rcpp-version.txt 

find . -name \*~ | xargs rm -f

exit 0
